### ISSUE TITLE
register Ramses and OPUS-DS sensors

### ISSUE THREAD

**Issue by tcarval** [nvs-vocabs/ArgoVocabs#1]
Henry B. requests two new sensors for German BGC-Argo floats to be deployed in early 2021.
These sensors are pilot stage 1, their data will be distributed in the "aux" (unregulated) directory

**OPUS-DS (in Spectrophotometers)**
SENSOR_MODEL	OPUS_DS
SENSOR_MAKER	TRIOS
COMMENTS	UV absorption to derive nitrate and bisulfide (TRIOS)
SENSOR   	SPECTROPHOTOMETER_NITRATE, SPECTROPHOTOMETER_BISULFIDE
SHORT SENSOR NAME	OPUS
update comment	pilot stage

**RAMSES (in Radiometers)**
SENSOR_MODEL	RAMSES_ACC
SENSOR_MAKER	TRIOS
COMMENTS	Hyperspectral radiometer 256 channels (TRIOS) with cosine detector to measure irradiance in water (at wavelength <nnn> specified in Table 3 BGC-Argo parameters list)
SENSOR    	RADIOMETER_DOWN_IRR<nnn>, RADIOMETER_PAR
SHORT SENSOR NAME	RAMSES
update comment	pilot stage

**TriOS in Reference Table 26**
SENSOR_MAKER	TRIOS
Description	TriOS GmbH

**Related tables**
Reference table 25: SENSOR
Reference table 26:  SENSOR_MAKER
Reference table 27: SENSOR_MODEL
Reference table 28: PLATFORM_MODEL

**Comment by tcarval** [comment]
OPUS-DS and RAMSES sensors are now declared on http://tinyurl.com/nwpqvp2
**Should be formally approved by Mathieu or John (the tables 22 - 28 editors)**

**Comment by mbelbeoch** [comment]
ok for me. I add this in the OceanOPS DB as well.

**Comment by tcarval** [comment]
Thank you Mathieu!
