### ISSUE TITLE
Create R27-R26 mappings for latest R27 additions

### ISSUE THREAD

**Issue by vpaba** [nvs-vocabs/ArgoVocabs#118]
Hi @tcarval ,

I have created a file with a list of suggested R27-R26 mappings for the latest codes that were added to R27.

Please, could you review and submit via the Vocab Editor (https://vocab.nerc.ac.uk/editor/bulk_upload_mappings/) if you're happy with them? [R27_R26_mappings_insert.csv](https://github.com/nvs-vocabs/R27/files/13073067/R27_R26_mappings_insert.csv)

I wasn't sure what manufacturer to map RAFOS to - if any - but please do add it to the list if you know the appropriate mapping in R26 (or if a new R26 entry needs creating first).

Thank you,
Violetta

**Comment by tcarval** [comment]
I updated Violetta's file 
[R27_R26_mappings_insert.csv](https://github.com/user-attachments/files/16948257/R27_R26_mappings_insert.csv)
