### ISSUE TITLE
RBR pressure and CTD manufacturer name/model updates and additions

### ISSUE THREAD

**Issue by matdon17** [nvs-vocabs/ArgoVocabs#13]
Back in July 2020, there was a suggested update to RBR CTD entries for pressure and CTD manufacturer name and model.

This covered L2 gen, L2 gen with CT cell and L3 gen (where 'gen' I assumed stood for generation).

There were 2 types of RBR pressure sensor and 4 types of RBR CTD that needed adding/modifying to the SENSOR_MAKER and SENSOR_MODEL reference tables R26 and R27.

Primary contact Mathieu Belboech.

**Comment by matdon17** [comment]
It was also noted by Claudia Schmid that RBR manufacturer an oxygen sensor which is due to be trialled on a WHOI float.

**Comment by tcarval** [comment]
No additional request for new RBR sensors entries
