### ISSUE TITLE
Mappings

### ISSUE THREAD

**Issue by vpaba** [nvs-vocabs/ArgoVocabs#29]
To create mappings (i.e. 'links') between concepts in related Argo collections, and between Argo collections concepts and concepts in related external collections.

Planned mappings at collection level are depicted below:

![Argo_collections_mappings](https://user-images.githubusercontent.com/43376757/133409803-6a3efd04-3ee3-47c6-9073-bbe0c9cb38d9.png)

**Comment by vpaba** [comment]
@nvs-vocabs/avtt Mappings between R27 concepts (SENSOR_MODEL) and related R26 concepts (SENSOR_MAKER) have been created and are now visible on the NVS: http://vocab.nerc.ac.uk/search_nvs/cmap/?a=R27&b=R26

**Comment by tcarval** [comment]
I uploaded these mappings R27-R26:
DRUCK_10153PSIA
ECO_FLBBFL
ECO_FLBBFL_AP2
GDF
SBE61_V5.0.10
SBE61_V5.0.12
SBE61_V5.0.9
