### ISSUE TITLE
Tables 26 27: SBE61_V5.0.9  DSB301-10-C85 QUARTZDYNE sensors 

### ISSUE THREAD

**Issue by tcarval** [nvs-vocabs/ArgoVocabs#31]
**SBE61_V5.0.9 sensor model**
The SBE61_V5.0.9 sensor model is currently rejected.
On December 10th 2021 it was added in the SENSOR_MODEL table 27

**QUARTZDYNE sensor maker**
The QUARTZDYNE sensor maker is currently rejected.
On December 10th 2021 it was added in the SENSOR_MAKER table 26

**DSB301-10-C85 sensor model**
The DSB301-10-C85 sensor model is rejected
Please use "QUARTZDYNE_DSB301-10-C85" from SENSOR_MODEL table 27

See also https://github.com/nvs-vocabs/R27/issues/4

_Dac:                'aoml'
File:               'sio_20211110181548.tar.gz:::5906433_meta.nc'
Type:               'META-DATA'
Version:            '3.1'
PI Name:            'NATHALIE ZILBERMAN'
Current Time (UCT): Wed Nov 10 19:45:11 2021
Reason:
  SENSOR_MODEL[2]: 'SBE61_V5.0.9' Status: Invalid
  SENSOR_MODEL[3]: 'SBE61_V5.0.9' Status: Invalid
  SENSOR_MAKER[4]: 'QUARTZDYNE' Status: Invalid
  SENSOR_MODEL[4]: 'DSB301-10-C85' Status: Invalid_

**Comment by ClaudiaAOML** [comment]
QUARTZDYNE_DSB301-10-C85 as well as DSB301-10-C85 are currently rejected by the format checker.

Based on discussion during ADMT22 (should manufacturer be part of sensor model; my understanding is: we will use as sensor model what the manufacturer uses and not revise it by adding the manufacturer): I think it will have to be DSB301-10-C85, but I'm not sure.

**Comment by tcarval** [comment]
This action was complete in December 2021

**Comment by tcarval** [comment]
The MENSOR sensor maker was missing in reference table 26. It is now registered.

ref_table-26:MENSOR | MENSOR | A manufacturing company located in San Marcos, Texas (United States of America), specialised in precision pressure products.    | 22/10/2023 | added by T. Carval for SOLO
