### ISSUE TITLE
HM4000 and Xuanwu (HM6000) new entries in R23 and R08

### ISSUE THREAD

**Issue by vturpin** [nvs-vocabs/ArgoVocabs#34]
Last year QNLM (National Lab. for Marine Science and Technology, Qingdao) deployed 9 HM4000 floats in the NW Pacific.
It's a pilot deployment for China Deep Argo. Those floats are equipped with SEB61 and RBR deep CTDs, and some of them
have obtained reliable T/S profiles. 
They are now ready to submit observations into GDACs via CSIO DAC.
Could we add HM4000 and HM6000 (i.e. Xuanwu and deep Xuanwu) into [R23](http://vocab.nerc.ac.uk/collection/R23/current/) for data distribution?
Suggested code : 
ID           |  Pref label        | definition
HM4000 | HM4000 float | HM4000 float
Xuanwu | Xuanwu Deep float | HM6000 float

**Comment by vturpin** [comment]
Note that : 
Xuanwu is one of China’s Four Sacred Creatures of the Heaven in ancient mythology, consisting of a tortoise and a snake coiling around it. It’s been seen as a symbol of longevity and auspice. Named after this legendary creature, Xuanwu carries the expectation of embracing a steady and sound performance, thus contributing Chinese wisdom to the understanding of the ocean. As “Xuanwu” follows the Mandarin phonetic system of Pinyin, the pronunciation is more like “shine-woo” or “sh-wan-woo”

**Comment by vturpin** [comment]
Also, I am a bit confused between R08 and R23. I understand than when new platform_type is accepted in R23, A R08 (instrument_type) code must be delivered at the same time ? Do you need extra information on the standard sensor onboard to deliver R08 code ?

**Comment by mscanderbeg** [comment]
Hi Victor.  R08 is based on WMO codes and is a number whereas R23 is a text field and is maintained by Argo.  
I agree to adding HM4000 and HM6000 to R23 to help start the flow of data from these floats.  I admit that I do not know how to get a WMO code added to table 1770 for the HM4000 and HM6000.

**Comment by apswong** [comment]
Hi Victor.  R08 is a subset of WMO code table 1770.  In the past, when a new platform emerged and we needed a new WMO_INST_TYPE in Ref Table 8 (now R08), Mathieu Belbeoch (in his former capacity at JCOMMOPS) was the person who would request a new code from WMO.  So you may want to ask him how that should be done now.

As an aside: I was told that the current R08, which combines float platform/sensor, is not a good way to go, as it is multiplying the need for new codes (e.g. instead of one code for APEX floats, we now have APEX with SBE, APEX with RBR, etc.).  Can we please open a new Github ticket for that issue?

**Comment by vturpin** [comment]
Hi Annie, Megan,
Thanks for the inputs, I indeed asked Mathieu and I have a pretty clear procedure to move on with R08.
I agree with you that this is not a very convenient way to go "platform+sensor" and I agree to open an issue to this regard. I think we should include in the discussion the relvant peron at WMO. 
My contact is : Anna Milan [amilan@wmo.int](mailto:amilan@wmo.int). I also have this link to share : https://github.com/wmo-im/CCT/issues/24
and the ref table : https://docs.google.com/spreadsheets/d/1Aw8B7FFUjG4e9MveD5qqvI7ZbB-z_x32IQnpHZbXVZA/edit#gid=1
However, this will probably take time to solve and I will request R08 new entry for "HM4000" and "Xuanwu" floats to move on.

**Comment by vturpin** [comment]
> I agree to adding HM4000 and HM6000 to R23 to help start the flow of data from these floats.

@mscanderbeg just to be clear, the request form Zenghong Liu and the QNLM is to name the float "HM4000" and "Xuanwu" following this : 
ID           | Pref label                | Alt label
HM4000 | HM4000 float         | HM4000 float
Xuanwu  |  Xuanwu Deep float | HM6000 float

**Comment by vpaba** [comment]
Hi @vturpin, @mscanderbeg and @apswong,

Thanks for the comments and discussion. We should absolutely go ahead and create HM4000 and Xuanwu in R23. 

One thing that's not yet clear to me is the associated PLATFORM_TYPE_KEY code. This is currently captured in the description fields for each R23 term (http://vocab.nerc.ac.uk/collection/R23/current/)

My first question is whether this is something still useful that we want to continue maintaining? 
If so, would you know who has been in charge of assigning these codes to each PLATFORM_TYPE (now R23) entry, so that we can ask for new ones to be assigned to HM4000 and Xuanwu?

**Comment by vpaba** [comment]
Hello, please note that the two R23 entries were created, alongside a new R24 (platform maker) entry. These are described in GitHub issues https://github.com/nvs-vocabs/R23/issues/2 and https://github.com/nvs-vocabs/R24/issues/1.

Once we know about the PLATFORM_TYPE_KEY code for the new R23 entries, I will update their description accordingly.

Will leave this issue open until we have the new entries requested created in R08/WMO as well, as followed up by @vturpin. Good point about R08 @apswong, we should involve the relevant contact at WMO to have this discussion with, as Victor suggested.

Please let me know if you spot any issues with the new NVS creations.

**Comment by tcarval** [comment]
**Message for Thierry to Zenhong and Victor**

Hello Zenghong and Victor,
Thank you for the sample files.
You are correct, the WMO instrument code 870 is not for HM4000 or HM6000 (according to the format checker, it is for NAMI).
Victor, can we assume that the new WMO instrument codes will be 881/HM4000 and 882/HM6000 ?
I also added a new entry in ref_table-27 for SBE61CP_V7.2.5

Zenghong, is the mention of HSOE and QNLM correct in ref_table-23 (HSOE is the manufacturer, QNLM the customer) ?

With the additions below in the reference tables, HM4000 and HM6000 files will be accepted on GDAC.
Let’s wait for Victor answer.
Kind regards,

Thierry


ref_table-23:
HM4000 | 700 | 881 | HSOE | Xuanwu float manufactured by HSOE for QNLM - Qingdao Pilot National Laboratory for Marine Science and Technology | 
HM6000 | 700 | 882 | HSOE | Xuanwu deep float manufactured by HSOE for QNLM - Qingdao Pilot National Laboratory for Marine Science and Technology | 

ref_table-8:
881 | HM4000
882 | HM6000

ref_table-27:
SBE61CP_V7.2.5 | SBE |  | CTD_PRES, CTD_TEMP, CTD_CNDC | CTD | 08/07/2022 | added by T. Carval for Z. Liu

**Comment by vturpin** [comment]
Hi Thierry, Zenghong,

I pushed this issue on the appropriate location :  https://github.com/wmo-im/CCT/issues/110
I suggest we move on with those entries and see when they are accepted.

Previous request took about 4 month to be accepted.

**Comment by tcarval** [comment]
Message from Zenghong
The manufacturer of HM4000 and HM6000 (deep Xuanwu) will be changed from HSOE to QNLM.

**Comment by tcarval** [comment]
> Message from Zenghong The manufacturer of HM4000 and HM6000 (deep Xuanwu) will be changed from HSOE to QNLM.

It will not be possible to change the manufacturer from HSOA to QNLM; if you want to have both possibilities (HSOA for now and QNLM in the future), we'll have to create a new instrument code for QNLM floats.

**Comment by tcarval** [comment]
The file format checker on Coriolis side is updated to accept Xuanwu files.
The new entries in the reference tables are: 


**ref_table-23**
HM4000 | 700 | 881 | HSOE | Xuanwu float manufactured by HSOE for QNLM - Qingdao Pilot National Laboratory for Marine Science and Technology | 
HM6000 | 700 | 882 | HSOE | Xuanwu deep float manufactured by HSOE for QNLM - Qingdao Pilot National Laboratory for Marine Science and Technology | 

**ref_table-8**
881 | HM4000
882 | HM6000

**ref_table-27**
SBE61CP_V5.0.1 | SBE |  | CTD_PRES, CTD_TEMP, CTD_CNDC | CTD | 08/07/2022 | added by T. Carval for Z. Liu

**Comment by tcarval** [comment]
Remaining actions

- Mike to install new reference tables on US GDAC
- - Victor to ensure that instruments 881 and 882 are declared on WMO vocabulary server

**Comment by vturpin** [comment]
The two reference have been added to the WMO Common Code Table C-3 Instrument make and type for water temperature profile measurements.
See: https://github.com/wmo-im/CCT/issues/110 

The issue can be closed

**Comment by vturpin** [comment]
Maybe we should wait to see "HM4000" and "Xuanwu" here : https://github.com/wmo-im/CCT/blob/master/C03.csv before closing

**Comment by vpaba** [comment]
Hi @vturpin and @tcarval, I am just reviewing the Argo collections and noticed that the XUANWU/HM6000 concept is a special case in R23, as the ID (XUANWU) is different from the Alt Label (HM6000). For all other concepts in R23, ID = Alt Label. The same can be said for numerous (but not all) Argo collections.

I was wondering - what are DACs using to populate the PLATFORM_TYPE (or what does the manufacturer would like DACs to use) - XUANWU or HM6000? If the former, would you be happy with replacing the Alt Label with XUANWU? HM6000 is mentioned in the description: http://vocab.nerc.ac.uk/collection/R23/current/XUANWU/

This would make this entry consistent with all others in R23; and also clarify things for DACs and M2M programs as well. Happy to discuss this in case.

Thanks for your help,
Violetta

**Comment by vturpin** [comment]
Shall we ask Zenghong Lui about it maybe ? 
As HM6000 is mentioned in the description the proposed solution looks ok to me.

On the other hand, what is the use of alt_label if it must be similar to ID?

**Comment by tcarval** [comment]
HM4000 and Xuanwu (HM6000) are registered in R23 and R08 tables.
So I close the ticket.
