### ISSUE TITLE
Please add SBE41N_v5.3.5 in R27

### ISSUE THREAD

**Issue by ksato-aopc** [nvs-vocabs/ArgoVocabs#37]
A float (WMO: 2903666) with SBE41N_v5.3.5 deployed in 2021 had been inactive, so we added END_MISSION_DATE to its metafile and sent it to GDAC. But it was rejected by File Checker because SBE41N V5.3.5 was not in R27. Please add SBE41N_v5.3.5 to R27.
Thank you.
Kanako SATO (JAMSTEC)

**Comment by tcarval** [comment]
The sensor is now added in R27 table.
The File format checker V2.7.5 now accepts this sensor.

**Comment by ksato-aopc** [comment]
@tcarval Thank you very much.
