### ISSUE TITLE
How to record an Argo float ASD - Abrupt Salty Drift

### ISSUE THREAD

**Issue by tcarval** [nvs-vocabs/ArgoVocabs#38]
A series of floats are concerned with ASD : the Abrupt Salinity Drift of their salinity sensor. See https://argo.ucsd.edu/argo-salty-drift-salinity-data-issue-notice-2021/

To identify these floats, this proposal recommends to store the ASD information in  : 

- the float metadata file, variable ANOMALY, in the "csv" with two possible anomalies
  - **ASD-AbruptSalinityDrift:Confirmed**
    - This float is affected by ASD
  - **ASD-AbruptSalinityDrift:NotConfirmed**
    - This float is in the list of potential ASD, the actual salinity drift is not confirmed

Examples:
ANOMALY = "ASD-AbruptSalinityDrift:NotConfirmed"
This float has one anomaly : it is in the list of potential ASD, but the ASD is not confirmed

ANOMALY = "ASD-AbruptSalinityDrift:Confirmed,ending_cause_category:hardware,ending_cause:ballast"
This floats has two anomalies : a confirmed ASD and an end of life due to hardware problem.

**Comment by tcarval** [comment]
Les disques iota1 et iota2 sont redevenus disponibles vers 14:00
Le sendmail de voo-curacao a été réactivé vers 15:10, il avait mis en attente 1200 messages de données
Les 14 crontab Coriolis ont été réactivées vers 15:15
Il n'a pas été utile de redémarrer les 14 serveurs Coriolis.

**Comment by delphinedobler** [comment]
I think the naming you propose fine. I was wondering whether we should add something indicating the cycle when it began, such as ASDAnomalyStartCycle:xx . 
The second item is the choice of colon to separate anomalies. If we ensure that namings of anomalies are constraint never to use colon, then it is fine. The same comment if we used semi-colon ";". I sometimes use the pipe sign "|", which has less probability to be used.

**Comment by delphinedobler** [comment]
Birgit comments: Do we really need the "notConfirmed" cases ? Can't it wait until the DMoperator solved the issue and just put the float on greylist in the meanwhile ?

**Comment by tcarval** [comment]
ASD-AbruptSalinityDrift:NotConfirmed" indicates that the sensor has a serial number in the list the potentially affected instruments. I think that this information is of interest.
Maybe should we have one more term for the sensors that are in the list of potentially affected, that have been checked by PI and are actually not affected by ASD:
- ASD-AbruptSalinityDrift:CheckedConfirmed
- ASD-AbruptSalinityDrift:CheckedNotAffected
- ASD-AbruptSalinityDrift:Unchecked

**Comment by tcarval** [comment]
**ADMT-23 decision**
Record ASD as

**Comment by cgourcuf** [comment]
I understood that we would not do this.

**Comment by apswong** [comment]
@tcarval. Including ASD as part of the ANOMALY vocabulary in the meta file is okay, but I suggest to not include ASD as part of the FLOAT_ENDING_CAUSE vocabulary, because it does not end the float's life - it merely ruins the salinity data.

**Comment by tcarval** [comment]
@apswong , hello Annie,
I think that to complete this issue, a sentence could be added in the « Argo Quality Control Manual For CTD and Trajectory Data » https://doi.org/10.13155/33951, chapter §3.6.4

> _3.6.4. Examples of unadjustable salinity data – Abrupt Salty Drift (ASD)
> …
> When ASD is confirmed, record the information in the ANOMALY variable of the float metadata file with this keyword : ASD:AbruptSaltyDrift
> …_

We may also add "from cycle #x" ... or not (to avoid consistency errors)

**Comment by tcarval** [comment]
Thank you Annie, so I close the ticket.
