### ISSUE TITLE
Investigate Attribute Convention on Dataset Discovery (ACDD) 1.3

### ISSUE THREAD

**Issue by tcarval** [nvs-vocabs/ArgoVocabs#39]
Consider whether a significant change to the management of metadata should be assessed, such as moving some variables into global attributes, and adoption of the Attritribute Convention on Dataset Discovery (ACDD)
- https://wiki.esipfed.org/Attribute_Convention_for_Data_Discovery_1-3

**Comment by vturpin** [comment]
I am happy to participate to this task. However I suspect this may be more impactfull than expected
