### ISSUE TITLE
bgc-Argo in a profile file the first profile has to be the core-Argo profile

### ISSUE THREAD

**Issue by tcarval** [nvs-vocabs/ArgoVocabs#45]
Some DACs produced BGC-Argo files whose first profile is not the core-Argo profile.
This incorrect position damages  the synthetic profile with invalid P, T,S columns
The problem was noted on some CSIRO files and possibly others.

**Comment by apswong** [comment]
Hi @tcarval, I am in communication with the CSIRO team about this. I hope to have this resolved soon.

**Comment by tcarval** [comment]
In the Argo NetCDF manual, it is explicitly mentioned in §3.16 "Reference table 16: vertical sampling schemes" that the profile with N_PROF=1 is required to be the Primary sampling profile.
This nvs-vocabs ticket can be closed, no specific vocabs action is needed.
