### ISSUE TITLE
Expansion of the pH SENSOR_MODEL names, with potential firmware version specification

### ISSUE THREAD

**Issue by tlmaurer** [nvs-vocabs/ArgoVocabs#47]
Hello,

The current SENSOR_MODEL definitions for pH sensors on BGC-Argo floats are currently limited to "DURA" (MBARI) and "SEAFET" (SEABIRD) within the Argo system.  Both MBARI and SBS have upgraded pH sensor types in development (Gasket DuraFET, and pressure-compensated pH sensor, respectively), with a limited number already deployed on floats in the testing phase.  There is thus a need to expand the pH SENSOR_MODEL vocabulary to include these newer versions.  It has been suggested that the latest MBARI sensor type be labelled "DURAV2", while SBS has identified their latest model as "SBS-58".  Considering the discussion on sensor firmware version (https://github.com/nvs-vocabs/ArgoVocabs/issues/55)  and @apswong latest comment, DURAV2 might be best left as "DURA", with an alternate SENSOR_FIRMWARE_VERSION specification, compared to the pre-existing DURA model.  Thoughts?

**Comment by tcarval** [comment]
Submitted to NVS
