### ISSUE TITLE
ECO_FLBBFL

### ISSUE THREAD

**Issue by catsch** [nvs-vocabs/ArgoVocabs#48]
Hi all, 

a new ensemble for an ECO3 sensor is at sea, here are the suggestions of Seabird, 
ECO_FLBBFL
ECO FLBBFL sensor package with two chlorophyll fluorometers and one scattering meter, 

Description

A three-channel optical sensor fitted with two single-wavelength chlorophyll fluorometers and a single-angle scattering meter, depth-rated to 2000 m and designed for float applications. The two fluorometers are configured to detect chlorophyll-a fluorescence at 470 nm (excitation) / 695 nm (emission) wavelengths and chlorophyll-a fluorescence at 435 nm (excitation) / 695 nm (emission) wavelengths respectively, whereas the scattering meter (in-water centroid angle of 124 deg) is configured to measure backscattering at 700 nm wavelength. The instrument is part of the Environmental Characterization Optics (ECO) series tools, manufactured by Sea-Bird Scientific.

thoughts ?

**Comment by tcarval** [comment]
ECO_FLBBFL is submitted to NVS vocabulary server.
