### ISSUE TITLE
CTD_TEMP_CNDC in R25

### ISSUE THREAD

**Issue by apswong** [nvs-vocabs/ArgoVocabs#50]
I would like to request a new entry in R25 "SENSOR".  It is CTD_TEMP_CNDC.

TEMP_CNDC is the internal temperature of the conductivity cell.  For RBR CTDs, measurements for TEMP and TEMP_CNDC come from two separate thermistors.  DACs will need CTD_TEMP_CNDC to record predeployment calibration information in the meta file separately from CTD_TEMP.

**Comment by BrianKingNOC** [comment]
@vpaba I'd like to reactivate this

Our work with sensor makers to distribute complete metadata that is consistent with NVS is maturing, and looks likely to involve live checking of some fields against NVS tables. Therefore the tables need to be complete, and CTD_TEMP_CNDC is needed in the online version of R25.

**Comment by tcarval** [comment]
@apswong , @BrianKingNOC  : All temperature parameter names start with "TEMP"
Can we add "TEMP_CNDC_CTD" : "External temperature of the conductivity sensor" 
Can you confirm that on a RBR sensor, there is a temperature sensor on the CTD and another distinct temperature sensor used with CNDC ?

**Comment by BrianKingNOC** [comment]
@tcarval : R25 is the list of SENSORs not PARAMETERs

SENSORs tend to begin with something to do with the instrument, eg CTD_TEMP or TRANSMISSOMETER_CP660

So I would suggest the SENSOR should definitely be CTD_TEMP_CNDC, and yes it is a different device that measures temperature in a different place, and will likely have its own SENSOR_SERIAL_NO

The PARAMETER it measures can be TEMP_CNDC, which sits alongside TEMP_DOXY and TEMP_CPU_CHLA, starting with TEMP

**Comment by tcarval** [comment]
My mistake, I'll add CTD_TEMP_CNDC in R25

**Comment by tcarval** [comment]
I added CTD_TEMP_CNDC in R25 (both NVS and format checker)
- Identifier: CTD_TEMP_CNDC
- Prefered label: Temperature sensor for conductivity on a CTD
- Definition: Specific temperature sensor used with conductivity to calculate salinity on a CTD

New release of the format checker:
https://github.com/euroargodev/ArgoNetCDF/releases/tag/v2.8.8
