### ISSUE TITLE
R08:  new entries - APEX_D RBR

### ISSUE THREAD

**Issue by vturpin** [nvs-vocabs/ArgoVocabs#59]
We need to add "APEX_D RBR" to the R08. 

The request has bee, submitted at https://github.com/wmo-im/CCT/issues/115 for addition to the CCT C-3 (forme code table 1770)

This entry could be added to R08 ahead of the official addition to the CCT C-3 (https://github.com/wmo-im/CCT/blob/master/C03.csv and https://library.wmo.int/doc_num.php?explnum_id=11283)

**Comment by tcarval** [comment]
Hello Victor,
Should the format checker accept APEX_D RBR right now, if such floats are already deployed ?

**Comment by vturpin** [comment]
This was a request from Argo Deep chairs. So yes I think one is already deployed or will be deployed very soon.




[Logo  Description automatically generated]



Victor TURPIN

Technical Coordinator Argo, OceanGliders & AniBOS

1625 Route de Sainte-Anne, 29280 Plouzané - France

+33 2 29 00 85 50

www.ocean-ops.org<https://www.ocean-ops.org/>

 <https://twitter.com/oceanops_goos> [cid:e819ca38-c994-47ee-809b-0e53af931d72] <https://twitter.com/oceanops_goos>  <https://m365.eu.vadesecure.com/safeproxy/v4?f=ARY6_KJ4MW5_GKvN34TR_qBhOf2KQ1OmRFeJZHcr_x_bl2CdzrEx2j8udBnCX8EN&i=aJ8CJO41t9Yz8bmvQsvKxPCmqCEV9HZDJqVadUCqS6Gw6EkIkJ_oKIjT6bZufV83fsMJyvk2ytRSnLsWyAhBBg&k=JbdT&r=KhKSltL4FQ1bgBb5V0zKl_SAdMvEK7a-HwX-YJz6FsQEKtSzwlh63uApTeH3VFCk&s=2381da01f04874f66347bb95dd57b3a871507b07cb72bfccc202c1cbe226422c&u=https%3A%2F%2Fwww.youtube.com%2Fchannel%2FUCm996CXe9BQZQKHguGMhtWg> [cid:691473af-9f85-45db-9e11-0a5624f1cd89] <https://www.youtube.com/channel/UCm996CXe9BQZQKHguGMhtWg>

________________________________

**Comment by tcarval** [comment]
Done : https://github.com/euroargodev/ArgoNetCDF/releases/tag/v2.8.6
