### ISSUE TITLE
R40 add entries

### ISSUE THREAD

**Issue by RomainCancouet** [nvs-vocabs/ArgoVocabs#64]
Hi,
Could you please add Colin STEDMON in the reference table R40 for PI_NAME? Alternatively could you add me as editor of the table so I could update it myself?
Thanks,
Romain

**Comment by RomainCancouet** [comment]
Hello @vpaba could you please remind me who could edit such table, and if the concerned persons receive a notification directly if for instance #R40 label is used in the tag of the issue?
Thanks

**Comment by gwemon** [comment]
Hello @RomainCancouet, Vi is on leave at the moment, She will be back on the 12th July.
I looked at the R40 and the people who can edit are: @tcarval , crbilhm, Guillaume, mkrieger.
We could add Colin when Vi is back? Is that early enough for you?
We don't currently have an automated way to notify editors. It would be nice to have this functionality. Something that would be worth investigating. If you are already aware of a way to do this in Github pls let us know.

**Comment by tcarval** [comment]
I tried to add Colin in R40 table

- PI0230
- Colin STEDMON

_Single insert: PI0230 Oracle Error - potentially due to not well-formed XML_

**Comment by RomainCancouet** [comment]
@gwemon could you please add me as editor of R40? I could see if I have the same error as Thierry?

**Comment by RomainCancouet** [comment]
> Hello @RomainCancouet, Vi is on leave at the moment, She will be back on the 12th July. I looked at the R40 and the people who can edit are: @tcarval , crbilhm, Guillaume, mkrieger. We could add Colin when Vi is back? Is that early enough for you? We don't currently have an automated way to notify editors. It would be nice to have this functionality. Something that would be worth investigating. If you are already aware of a way to do this in Github pls let us know.

https://github.com/marketplace/actions/issue-label-notifier ?

**Comment by gwemon** [comment]
> @gwemon could you please add me as editor of R40? I could see if I have the same error as Thierry?

> @gwemon could you please add me as editor of R40? I could see if I have the same error as Thierry?

@RomainCancouet you now have the role (using your euro-argo email address). Can you try? You might need to clear the cache just in case.

**Comment by tcarval** [comment]
I tried the editor from Chrome and Firefox (and failed )

**Comment by RomainCancouet** [comment]
Hi, I have tried and have the following message: Single insert: PI0230, successfully inserted. So I reckon it worked although I am not able to see the updated R40 table yet, it might takes some time to get last entries updated

**Comment by gwemon** [comment]
Hi @RomainCancouet. Very good. So it works for you but not for @tcarval. That is very strange. It is strange also that Thierry tried to update 2 vocabs and got the same error each time. @tcarval could you try another one again and just enter TEST in all the fields and try submitting. If it works we will delete it before pushing the changes to the NVS.
Romain, regarding the update to R40, this will happen tomorrow after the overnight publication. The public facing NVS publication process is never immediate and when using the vocab editor there is an additional step.  When content is submitted via the vocab editor, it goes into a holding table. A message is sent to the NVS gatekeepers who review it before queueing the new terms for the overnight publication.

**Comment by gwemon** [comment]
> I tried the editor from Chrome and Firefox (and failed )

@tcarval did you try after clearing the cache and from an incognito window too? We need to make sure we eliminate the most common issues before diving in the problem. Were you ever able to enter anything via the vocab editor or was this the first time you tried?

**Comment by tcarval** [comment]
@gwemon I tried several time during the last weeks, on different tables, always unsuccessful  😥
I tried from chrome or firefox, in anonymous mode, having cleared the cache.
No way.
What is Romain's secret to add a new term 🤔

**Comment by gwemon** [comment]
Thank you @tcarval we're going to check the logs and see if anything odd can be spotted. This is very puzzling indeed! Can I just ask one last question before doing that: is this the first time ever that you tried to load changes via the vocab editor?

**Comment by tcarval** [comment]
Hello @gwemon , I remember that last year I could upload terms during a training session.
Maybe was it on a test database ? Maybe my user interact with the wrong database ?

**Comment by RomainCancouet** [comment]
> Hi @RomainCancouet. Very good. So it works for you but not for @tcarval. That is very strange. It is strange also that Thierry tried to update 2 vocabs and got the same error each time. @tcarval could you try another one again and just enter TEST in all the fields and try submitting. If it works we will delete it before pushing the changes to the NVS. Romain, regarding the update to R40, this will happen tomorrow after the overnight publication. The public facing NVS publication process is never immediate and when using the vocab editor there is an additional step. When content is submitted via the vocab editor, it goes into a holding table. A message is sent to the NVS gatekeepers who review it before queueing the new terms for the overnight publication.

Hello @gwemon , it seems my request to add Colin STEDMON has been refused by NVS gatekeepers? At least I am not able to see the updated list on R40.

**Comment by gwemon** [comment]
Hello @RomainCancouet It might have been overlooked because of the issues Thierry had. I'll check with @vpaba.

**Comment by gwemon** [comment]
@RomainCancouet  @vpaba I had a look at our submission table and understand what happened. Romain you added the term to the vocab editor but forgot to the final step that commits  the changes by clicking the final submit to the NVS. So we can see the record in our tables but it is still flagged as "Pending" and not "Submitted" hence it wasn't picked up by our daily checks. We'll do that now and it will be live tomorrow.
