### ISSUE TITLE
NVS 27

### ISSUE THREAD

**Issue by ClaudiaAOML** [nvs-vocabs/ArgoVocabs#65]
Please add the following three sensors to NVS 27: 

SBE61_V5.0.9
SBE61_V5.0.10
SBE61_V5.0.12

Thank you.

**Comment by tcarval** [comment]
@ClaudiaAOML done: two SBE sensors added 
https://github.com/euroargodev/ArgoNetCDF/releases/tag/v2.8.3

**Comment by tcarval** [comment]
**To do list**
- [ ] update format checker
- [ ] update NVS

**Comment by tcarval** [comment]
SBE61_V5.0.10 and SBE61_V5.0.12 will wait for ADMT-24 to be registered in NVS.
However, they are accepted by the format checker, so valid in Argo data system.
