### ISSUE TITLE
R27 (Argo sensor models)

### ISSUE THREAD

**Issue by ClaudiaAOML** [nvs-vocabs/ArgoVocabs#68]
please add SBE41CP_V5.3.4 SBE41CP_V5.3.5 to R27 (Argo sensor models)

**Comment by mscanderbeg** [comment]
Hello.  I think we agreed at the last ADMT meeting to not include firmware versions in the SENSOR_MODEL field anymore.  That would mean that these sensor models could simply be SBE41CP.  We are looking for ways to store Sensor firmware version elsewhere.

**Comment by tcarval** [comment]
SBE41CP is valid on NVS and file checker
- NVS: http://vocab.nerc.ac.uk/collection/R27/current/SBE41CP/
- File checker line 16: https://github.com/euroargodev/ArgoNetCDF/blob/main/file_checker_spec/ref_table-27 

@ClaudiaAOML , can you use SBE41CP for now and wait for a future sensor_firmware version ?

**Comment by tcarval** [comment]
> SBE41CP is valid on NVS and file checker
> 
> * NVS: http://vocab.nerc.ac.uk/collection/R27/current/SBE41CP/
> * File checker line 16: https://github.com/euroargodev/ArgoNetCDF/blob/main/file_checker_spec/ref_table-27
> 
> @ClaudiaAOML , can you use SBE41CP for now and wait for a future sensor_firmware version ?

After email with Megan, I will accept SBE41CP_V5.3.4 SBE41CP_V5.3.5 in the file checker, but not yet on NVS as there will be a proposal to manage sensor model and firmware version separately.
