### ISSUE TITLE
ECO_FLBBFL_AP2

### ISSUE THREAD

**Issue by catsch** [nvs-vocabs/ArgoVocabs#70]
request from aoml, 
presently only ECO_FLBBFL is define
but the new sensor model provided by the manufacturer to aoml is now ECO_FLBBFL_AP2. would it be possible to add this new entry in the SENSOR_MODEL

**Comment by tcarval** [comment]
Hello, below the definition of ECO_FLBB_AP2

> ECO_FLBB_AP2 | WETLABS | Wetlabs Eco optical sensor packages with one fluorometer (type specified in SENSOR) and one backscattering meter (wavelength specified in SENSOR) mounted on an Apex float | FLUOROMETER_CHLA, BACKSCATTERINGMETER_BBP<nnn> | FLUOROMETER_CHLA, BACKSCATTERINGMETER_BBP<nnn> | ECO |  |  

What should we add for ECO_FLBBFL_AP2 ?

**Comment by tcarval** [comment]
Status of this ECO_FLBBFL_AP2

- [x] added on Coriolis GDAC
- [ ] added on US GDAC
- [ ] added on NVS
- [ ]

**Comment by catsch** [comment]
Thank you @tcarval
