### ISSUE TITLE
R03: Should units be part of the description and a preferred unit string ?

### ISSUE THREAD

**Issue by BrianKingNOC** [nvs-vocabs/ArgoVocabs#74]
Here is another R03 issue. This is prompted by the json metadata activity, but not confined to it.

Table R03 doesn't refer to the units for a parameter. The xls table that proceeded it had a lot of extra information about range (min/max) format/resolution etc. Range and numerical format have already had issues raised.

Now it is the turn for units.

For example the xls spreadsheet tells me TEMP should be 
degree_Celsius
although I need to go to another column to also see that that is in ITS-90.

This units info isn't actually recorded anywhere in the meta.nc. 
@jean-philippe Ranou pointed out to me that
PARAMETER_UNITS is supposed to refer to PARAMETER_ACCURACY And PARAMETER_RESOLUTION but not necessarily PARAMETER.

So the whole issue of where we record units is a bit incomplete. As far as I can tell, none of the Rxx tables, useable by machines, tell a machine what the units should be in Argo files, unless I have missed something.

In the data files, eg prof.nc, the PARAMETER has attributes including units, and the User Manual says those fields are specified in ref table 3. But they're not in NVS R03.

**Comment by tcarval** [comment]
For each R03 parameter, the unit is available as "related P06: *"
Example : https://vocab.nerc.ac.uk/collection/R03/current/TEMP/ 
<html>
<body>


Related | P06:[UPAA ](https://vocab.nerc.ac.uk/collection/P06/current/UPAA/)| Degrees Celsius
-- | -- | --



</body>
</html>

Do we miss something there ?

**Comment by BrianKingNOC** [comment]
Aha. Thanks @tcarval 

Looking at the page for TEMP
http://vocab.nerc.ac.uk/collection/R03/current/TEMP/
I didn't realise that related P06 would take me to units. That comes with experience I guess.

As it happens, TEMP_CNDC doesn't have the 'related' link.
http://vocab.nerc.ac.uk/collection/R03/current/TEMP_CNDC/


So if I follow TEMP, I find units are
"Degrees Celsius"
alt label 
"degC"

and for CNDC, I find
"Siemens per metre" with alt "S/m"


I saw the old xls sheet has
"degree_Celsius"
for all the temperatures parameters and
"mhos/m" for CNDC.

I'm quite happy to let P06 become the master reference.
I notice the user manual Page 23 has "degree_Celsius" in the example.

I guess the units attribute in the prof.nc file is autofilled  for all the parameters. Is there a plan to ask DACs to move over to the approved names in P06 linked from the parameters in R03 ?

In the json work, we might introduce a new unit field to accompany the parameter, chosen from R03/P06, to at least get things correct from the origin of the sensor.

**Comment by tcarval** [comment]
There is no plan to change the Argo units labels.
We'll check what is the best option on NVS to list the existing Argo units.
@vpaba , @gwemon, ideas ?

**Comment by tcarval** [comment]
These 5 tickets address similar topic : https://github.com/nvs-vocabs/ArgoVocabs/issues/78 https://github.com/nvs-vocabs/ArgoVocabs/issues/57 https://github.com/nvs-vocabs/ArgoVocabs/issues/95 https://github.com/nvs-vocabs/ArgoVocabs/issues/74 https://github.com/nvs-vocabs/ArgoVocabs/issues/98

I close 4 of them and keep https://github.com/nvs-vocabs/ArgoVocabs/issues/57
