### ISSUE TITLE
units for radiance  W/m^2/nm for DOWN but  W/m^2/nm/sr for UP ?

### ISSUE THREAD

**Issue by BrianKingNOC** [nvs-vocabs/ArgoVocabs#75]
The xls table for parameters 
[Argo physical parameters list: core-Argo and BGC-Argo, February 3rd 2023](http://www.argodatamgt.org/content/download/30910/209488/file/argo-parameters-list-core-and-b_20230203.xlsx)
tells me the units of DOWN_IRRADIANCE are

W/m^2/nm

But for UP_RADIANCE the units are

W/m^2/nm/sr

Is this distinction really correct ? That for up radiance the units are per unit of solid angle, but for down radiance the units are just per unit wavelength, presumably integrated over the whole uplooking hemisphere ?

If someone knows that this distinction is correct, then by all means say so and close the issue.

**Comment by EdLeymarie** [comment]
Yes, **Irradiance** here is plane irradiance and corresponds to the measurement of light coming from an entire hemisphere. The unit is W/m^2/nm
**Radiance**, on the other hand, is the light energy coming from a specific direction (in this case, upward ) within a given solid angle. thus the unit is W/m^2/nm/sr

https://www.oceanopticsbook.info/view/light-and-radiometry/geometrical-radiometry

**Comment by catsch** [comment]
+1 @EdLeymarie
