### ISSUE TITLE
Provide a method how 'phased-out' sensors can be marked in the SENSOR_MODEL table

### ISSUE THREAD

**Issue by HCBScienceProducts** [nvs-vocabs/ArgoVocabs#77]
SENSOR_MODEL reference table R27: The previous Excel reference table had a column named "deprecated" which probably referred to the label being accepted or deprecated (and later to be removed from the Excel file). I think a similar concept of "deprecated" entries exist in the NVS (see e.g. https://vocab.nerc.ac.uk/collection/C17/current/), which invalidates the label (?).

Argo has a concept how to phase in and accept new sensors into Argo ([§2.4.7.1.1.1" Float sensor status within Argo program"](https://docs.google.com/document/d/1vFLDlk4paPPUGUFVgTBn0QadrqVsmWy1fFL6eb2w6gE/edit#bookmark=id.cmkwxjaet7q1)) 

Innovation, however, also requires that there's a method how to phase out a sensor (for whatever reason). This requires a marking of some sort that the sensor in R27 is no longer approved/sanctioned by Argo, so that it is no longer used on new deployments by Argo.

While the problem may appear "symmetric" (=simply remove it from the R27 list, i.e., declare it "deprecated" in the NVS?), I'd think it's not: With phasing out a sensor we will still have this sensor and its (past) data in the system, which requires those entries to be accepted for Argo files (e.g., reprocessings that would otherwise be rejected by the file checker). 

So any suggestion is welcome of how to mark a phased-out sensor (with a label? Or a date?), that permits its past data to remain and being handled in the data system, while making it clear to users and implementers that no new deployments should be done.

**Comment by vpaba** [comment]
Hi @HCBScienceProducts,

Thanks for your question. Just a note to add that, from the NVS side, a 'deprecated' term is not removed from the server, and its URI still persists; it is however marked by a 'Deprecated' note.

Deprecated terms don't immediately appear in NVS search results unless the Deprecation status 'Deprecated' is ticked in the NVS search feature that's expanded when clicking on 'toggle advanced options'. 

This is a list of all deprecated R27 terms: https://vocab.nerc.ac.uk/search_nvs/R27/?searchstr=&options=identifier,preflabel,altlabel,status_deprecated&rbaddfilter=inc&searchstr2=

Currently, only one term in R27, 'DRUCK_10153PSIA', has been deprecated: https://vocab.nerc.ac.uk/collection/R27/current/DRUCK_10153PSIA/

In the JSON format of this NVS concept, this is marked by:
"deprecated" : "true"

In the RDF/XML format, this is marked by:
skos:note              "deprecated"@en ;

This marking would technically allow phased-out sensors to remain in the data system, and be handled as such if a system (e.g. GDAC file checker) knows how to query and process codes marked as 'deprecated'.

I hope this is helpful,

Thanks, Violetta

**Comment by tcarval** [comment]
This is our solution to deprecate Argo terms in NVS.
