### ISSUE TITLE
[R40] Modification and additions requested

### ISSUE THREAD

**Issue by delphinedobler** [nvs-vocabs/ArgoVocabs#84]
Modification to R40:
"Isabelle TAUPIER-LEPAGE" should be corrected to "Isabelle TAUPIER-LETAGE"
Additions:
Francisco DOS SANTOS
Markus JANOUT
Meike MARTINS

**Comment by MKrieger29** [comment]
Done:  
![image](https://github.com/nvs-vocabs/ArgoVocabs/assets/74649916/01737570-cad2-43ce-9932-2f3a1c8ecc27)
