### ISSUE TITLE
R23: GDAC rejects files with type SOLO_BGC

### ISSUE THREAD

**Issue by ClaudiaAOML** [nvs-vocabs/ArgoVocabs#85]
SOLO_BGC as instrument type gets rejected by the GDACs. Because of that we have to use SOLO_II. Not sure if I picked the right names as "assignees"  ...

**Comment by tcarval** [comment]
@ClaudiaAOML Hello Claudia, I'll check the content of AOML rejected metadata files and register on checker and NVS the new instrument type.

**Comment by tcarval** [comment]
There are 5 metadata files that were rejected by the format checker
ls -lah *_meta.nc
-rw-r----- 1 co_exp coriolis 105K Mar  6 19:19 2903867_meta.nc
-rw-r----- 1 co_exp coriolis 111K Mar 20 03:45 4903748_meta.nc
-rw-r----- 1 co_exp coriolis 105K Mar  6 18:45 4903750_meta.nc
-rw-r--r-- 1 co_exp coriolis  35K Mar 21 22:34 5906949_meta.nc
-rw-r----- 1 co_exp coriolis 107K Mar  8 00:13 6990583_meta.nc

2903867_meta.nc, 4903748_meta.nc.filecheck, 4903750_meta.nc 6990583_meta.nc : replace MBARI by SBE
    <error>SENSOR_MODEL/SENSOR_MAKER[6]: Inconsistent: 'SEAFET'/'MBARI'</error>

5906949_meta.nc : remove the empty LAUNCH_CONFIG_PARAMETER_NAME
    <error>LAUNCH_CONFIG_PARAMETER_NAME[27]: Incorrectly formed name ''</error>
    <error>CONFIG_PARAMETER_NAME[15]: Incorrectly formed name ''</error>

**Comment by tcarval** [comment]
@ClaudiaAOML  can you send me a SOLO_BGC metadata file ? 
In reference table 8, "SOLO_BGC" is a valid entry
ref_table-8:884 | SOLO_BGC, SBE
ref_table-8:885 | SOLO_BGC, RBR
ref_table-8:886 | SOLO_BGC_MRV, SBE
ref_table-8:887 | SOLO_BGC_MRV, RBR

**Comment by tcarval** [comment]
add SOLO_BGC in R23 and add SIO_IDG as the platform maker

**Comment by tcarval** [comment]
@ClaudiaAOML hello Claudia, I published a new version of the file checker to accept SOLO_BGC float type with SIO_IDG maker.
https://github.com/nvs-vocabs/ArgoVocabs/issues/85
