### ISSUE TITLE
R11: Updated with QC manual 3.8 add obsolete tests 10 and 11 and new test 26 in the table R11

### ISSUE THREAD

**Issue by delphinedobler** [nvs-vocabs/ArgoVocabs#86]
Two tests that are now obsolete should nonetheless be added to R11 table (with deprecated attribute), in particular because old profile files from the GDAC will contain the codes associated to these tests and we should be able to understand the meaning.

It concerns:
Test 10. Top and bottom spike test: declared obsolete in October 2003 at ADMT4 
test 10 binary ID: 1024
Test 11. Gradient test: declared obsolete in October 2019 at ADMT20
test 11 binary ID: 2048

The new test that should be added is test 26:
Test 26. TEMP_CNDC test applied to RBRargo3|2K, test added in July 2022.
CTD data (< 2000 dbar) (TEMP_CNDC is used in the long timescale thermal inertia correction for RBR salinity data.
This test aims to identify vertical profiles where TEMP_CNDC is of bad quality and thus
unsuitable for use in the real-time adjustment of RBR salinity data.)
test 26 binary id =  ? 67 108 864 ? (waiting for confirmation, binary id is missing in QC manual release 3.8)

**Comment by tcarval** [comment]
I tried to register the R11 tests 10 and 11 in NVS. An error message informs that these tests already exist, they are not publicly available, but as editor of R11 I can see them with a version 2.  @gwemon, Gwen can you confirm that this means that these terms are deprecated ?

I successfully registered  test 26 on NVS, it should appear within a few hours.

**Comment by tcarval** [comment]
> I tried to register the R11 tests 10 and 11 in NVS. An error message informs that these tests already exist, they are not publicly available, but as editor of R11 I can see them with a version 2. @gwemon, Gwen can you confirm that this means that these terms are deprecated ?
> 
> I successfully registered test 26 on NVS, it should appear within a few hours.

I just found the NVS syntax to detect deprecated terms (tests 10 & 11):
https://vocab.nerc.ac.uk/search_nvs/R11/?searchstr=&options=identifier,preflabel,altlabel,status_deprecated&rbaddfilter=inc&searchstr2=
