### ISSUE TITLE
R13: Complete the description of the areas

### ISSUE THREAD

**Issue by delphinedobler** [nvs-vocabs/ArgoVocabs#87]
In the NVS table R13, the description only provides the areas limits below 33°S. However, the map from the user manual details to which area marginal seas are associated to, and this information should be included in the NVS.

I propose to change the R13 concepts description as follows:
Atlantic ocean area: 
From 
 "The Atlantic/Pacific oceans boundary is at 70 deg W, whereas the Atlantic/Indian oceans boundary is at 20 deg E."
To:
"Below 30°S, the Atlantic/Pacific oceans boundary is at 70 deg W, whereas the Atlantic/Indian oceans boundary is at 20 deg E. The Caribbean Sea, the Mexico Gulf, the Mediterranean Sea, the Black Sea, the Baltic Sea, the Labrador Sea, the Baffin Bay and the Nordic seas (Greenland, Norwegian, Barents and Kara seas) are part of the Atlantic ocean area".

Indian ocean area:
From 
 "The Indian/Atlantic oceans boundary is at 20 deg E, whereas the Indian/Pacific oceans boundary is at 145 deg E."
To:
"Below 30°S, the Indian/Atlantic oceans boundary is at 20 deg E, whereas the Indian/Pacific oceans boundary is at 145 deg E. The Red Sea is part of the Indian ocean area".

Pacific ocean area:
From:
"The Pacific/Indian oceans boundary is at 145 deg E, whereas the Pacific/Atlantic oceans boundary is at 70 deg W."
To:
"Below 30°S, the Pacific/Indian oceans boundary is at 145 deg E, whereas the Pacific/Atlantic oceans boundary is at 70 deg W. The South China Sea, the Indonesian seas, the Laptev, Beaufort, East Siberian and Chukchi seas are part of the Pacific ocean area.

**Comment by tcarval** [comment]
I updated the ocean definitions as requested in NVS.
I replaced "°" with "degrees" and "E" with "east" (same for W, N, S).
The NVS should be updated within a few hors.
