### ISSUE TITLE
GDAC rejects files with SOLO_BGC

### ISSUE THREAD

**Issue by ClaudiaAOML** [nvs-vocabs/ArgoVocabs#89]
SOLO_BGC as instrument type gets rejected by the GDACs. Because of that we have to send them as SOLO_II floats.

**Comment by tcarval** [comment]
This ticket is a duplicate of https://github.com/nvs-vocabs/ArgoVocabs/issues/85

**Comment by ClaudiaAOML** [comment]
we are getting this from the format checker:   PLATFORM_TYPE/PLATFORM_MAKER: Inconsistent: 'SOLO_BGC'/'MRV'

SOLO_BGC can have the manufacturer MRV or SIO. I wish I had know what would happen for this float (2903886_meta.nc) earlier ...

**Comment by JohnEGilson** [comment]
SOLO_BGC_MRV is available in R08. However, it is not listed in R23. This is the source of the issue.  To be consistent with other SOLO family floats there should be a SOLO_BGC_MRV listed in R23.

SOLO_BGC_MRV :  MRV : 886 (other?) : PLATFORM_TYPE_KEY?

**Comment by tcarval** [comment]
Hello Claudia and John,
I added SOLO_BGC_MRV in R23
SOLO_BGC_MRV | 207 | 886 887 | MRV | MRV SOLO |

**Comment by tcarval** [comment]
Hello Claudia and John,
I added SOLO_BGC_MRV in R23
SOLO_BGC_MRV | 207 | 886 887 | MRV | MRV SOLO |

**Comment by tcarval** [comment]
The new release of the format checker is released: https://github.com/euroargodev/ArgoNetCDF/releases/tag/v2.8.11
