### ISSUE TITLE
Calibration variables standardisation

### ISSUE THREAD

**Issue by matdon17** [nvs-vocabs/ArgoVocabs#9]
Should we attempt to standardise variables containing information on calibrations?

There are an increasingly complicated range of calibrations to apply to:

- PREDEPLOYMENT_CALIB_EQUATION
- PREDEPLOYMENT_CALIB_COEFFICIENT
- PREDEPLOYMENT_CALIB_COMMENT
- SCIENTIFIC_CALIB_EQUATION
- SCIENTIFIC_CALIB_COEFFICIENT
- SCIENTIFIC_CALIB_COMMENT

It is complicated to manage standardisation, but if not standardised it is harder to make useful to users/future DAC & DM operators/PIs.  BGC has done this for PREDEPLOYMENT_* in cookbooks, but unconstrained in the scientific QC information. 
 There are examples for SCIENTIFIC_* in core DMQC in manual, but not exhaustive.

Can we/should we attempt to standardise these?

**Comment by tlmaurer** [comment]
I think we have certainly made progress on this topic in BGC for the SCIENTIFIC* fields, but it is somewhat ongoing (and will be for awhile) as we continue to develop protocols etc.  So-- I am closing this ticket for now.  If there are specific parameter fields that we are close to reaching precise standardization on, and needs final addressing, then let's open another ticket at that time.  Thanks!
