### ISSUE TITLE
Did the NVS server has changed the output format convention ????

### ISSUE THREAD

**Issue by gmaze** [nvs-vocabs/ArgoVocabs#91]
[Report from argopy user](https://github.com/euroargodev/argopy/discussions/376) indicates that the NVS server has changed the ld+json output format convention

A few weeks ago, the server was reporting something like this for a "concept":
```json
{
    "@id" : "http://vocab.nerc.ac.uk/collection/R01/current/BTRAJ/",
    "@type" : "skos:Concept",
    "identifier" : "SDN:R01::BTRAJ",
    "date" : "2020-04-04 15:05:33.0",
    "dc:identifier" : "SDN:R01::BTRAJ",
    "authoredOn" : "2020-04-04 15:05:33.0",
    "hasCurrentVersion" : "http://vocab.nerc.ac.uk/collection/R01/current/BTRAJ/1/",
    "version" : "1",
    "inDataset" : "http://vocab.nerc.ac.uk/.well-known/void",
    "deprecated" : "false",
    "versionInfo" : "1",
    "altLabel" : "BTRAJ",
    "definition" : {
      "@language" : "en",
      "@value" : "Argo float trajectory file containing CTD pressure data and data from one or more biogeochemical (BGC) parameters (dissolved oxygen, nitrate, pH, chlorophyll-a, particle backscatter, irradiance)."
    },
    "notation" : "SDN:R01::BTRAJ",
    "note" : {
      "@language" : "en",
      "@value" : "accepted"
    },
    "prefLabel" : {
      "@language" : "en",
      "@value" : "B-Argo trajectory"
    }
```

while the current server returns:
```json
    {
      "@id": "http://vocab.nerc.ac.uk/collection/R01/current/BTRAJ/",
      "pav:authoredOn": "2020-04-04 15:05:33.0",
      "pav:hasCurrentVersion": {
        "@id": "http://vocab.nerc.ac.uk/collection/R01/current/BTRAJ/1/"
      },
      "dce:identifier": "SDN:R01::BTRAJ",
      "pav:version": "1",
      "skos:notation": "SDN:R01::BTRAJ",
      "skos:altLabel": "BTRAJ",
      "dc:date": "2020-04-04 15:05:33.0",
      "owl:versionInfo": "1",
      "skos:prefLabel": {
        "@language": "en",
        "@value": "B-Argo trajectory"
      },
      "dc:identifier": "SDN:R01::BTRAJ",
      "skos:note": {
        "@language": "en",
        "@value": "accepted"
      },
      "owl:deprecated": "false",
      "void:inDataset": {
        "@id": "http://vocab.nerc.ac.uk/.well-known/void"
      },
      "skos:definition": {
        "@language": "en",
        "@value": "Argo float trajectory file containing CTD pressure data and data from one or more biogeochemical (BGC) parameters (dissolved oxygen, nitrate, pH, chlorophyll-a, particle backscatter, irradiance)."
      },
      "@type": "skos:Concept"
    },
```

All entries now have a prefix like `pav:`, `dce:`, `skos:`, `dc:`,`owl:` and `void:`

Sorry if I missed the change notice, are these changes documented somewhere ?
thanks
GM

**Comment by gmaze** [comment]
Above responses returned by https://vocab.nerc.ac.uk/collection/R01/current/?_profile=nvs&_mediatype=application/ld+json

**Comment by alko-k** [comment]
Hello @gmaze thanks for reporting the issue. I did manage to find the old jsonld and you are right that the prefixes were not there before. We did migrate the NVS to a new server so that is what caused the issue. We are now working to restore it. I will keep you updated.

**Comment by gmaze** [comment]
thanks @alko-k for the quick response
there is no need to restore it, [I already updated my code of interest](https://github.com/euroargodev/argopy/pull/378).
but it would be great to have some kind of warning before the next update like this, so that there is no breaking services in downstream applications

**Comment by gmaze** [comment]
> there is no need to restore it

except for other users obviously ;-)

**Comment by alko-k** [comment]
Thanks for the @gmaze and apologies for the disruption.  
Unfortunately it happened during migration of the NVS to upgraded servers, where such a change was not expected. We have not be approached by others yet, but I know that a lot of people are still on holidays. As I understand if we fix this now, it will break your code again. is that right?

**Comment by gmaze** [comment]
@alko-k 
If you move back to the previous format, yes this will break argopy again.
But changes are not very large, so I could fix argopy's code to handle both versions of the format

I will adapt to whatever you decide according to other user feedbacks
(If other users don't notice the change, I would be curious to see how they design their code to adapt *automatically* to such changes)

Basically, whatever the changes, it would be great to consider for end users some progressive implementation with deprecation warnings or some webpages where server updates are mentioned.
At Ifremer, there is also a "test" server where updates are deployed before production, which allows to detect such unexpected changes.

**Comment by alko-k** [comment]
Thanks for your comments @gmaze . 
Yes such a page for notifications of changes will be created soon.
