### ISSUE TITLE
Reference Table 1 : DATA_TYPE "Argo auxiliary meta-data" not in vocabulary

### ISSUE THREAD

**Issue by SBS-EREHM** [nvs-vocabs/ArgoVocabs#92]
Argo Auxilary Files also have a metafile, i.e., wmoid_meta_aux.nc.

For the DATA_TYPE field, it is currently populated with "Argo auxiliary meta-data", e.g.,

 DATA_TYPE = "Argo auxiliary meta-data        " ;

This label is not in Argo User's Manual Reference Table 1, p. 71  or the NVS R01 Vocabulary.

Eric Rehm
Sea-Bird Scientific

**Comment by tcarval** [comment]
I added “Argo auxiliary meta-data” data type in reference table 1.
However, "aux" files are not format checked, this is a suggestion, not mandatory.
