### ISSUE TITLE
Reference Table 1 : DATA_TYPE : "Argo meta-data" or "Argo metadata"

### ISSUE THREAD

**Issue by SBS-EREHM** [nvs-vocabs/ArgoVocabs#93]
The controlled vocab for DATA_TYPE is set in Reference Table 1.  One of the controlled values (ID=META) has a different label definition in the NVS R01 vocab ("Argo metadata") compared to that in the Argo User's Manual, V3.41, page 71: "Argo meta-data".    From a cursory look at some Argo wmoid_meta.nc files, it appears that the Argo User's Manual encoding is used in netCDF files, i.e.,

 DATA_TYPE = "Argo meta-data  " ;

https://vocab.nerc.ac.uk/collection/R01/current/
(Note the additional hyphen in Argo User's Manual version.)

The two definition should be reconciled to achieve machine-readable parsing of CDL and JSON files based on the vocabulary.

There is, I suppose, a separate issue here that some metadata fields in Argo netCDF files are encoded using labels ("Argo meta-data") as opposed to IDs ("META"), while other fields (e.g., "PLATFORM_FAMILY") are encoded using IDs.  Not sure how to raise that issue....

Thanks,

Eric Rehm
Sea-Bird Scientific

**Comment by tcarval** [comment]
The NVS label of META was corrected in October 2023 to the valid "Argo meta-data"
https://vocab.nerc.ac.uk/collection/R01/current/META/
