### ISSUE TITLE
Provide standard netcdf attributes for each parameter ?

### ISSUE THREAD

**Issue by gmaze** [nvs-vocabs/ArgoVocabs#95]
Would it be possible to further include in the description of each parameters the attributes we get in Argo netcdf files ?

For instance for TEMP:
```
		TEMP:long_name = "Sea temperature in-situ ITS-90 scale" ;
		TEMP:standard_name = "sea_water_temperature" ;
		TEMP:_FillValue = 99999.f ;
		TEMP:units = "degree_Celsius" ;
		TEMP:valid_min = -2.5f ;
		TEMP:valid_max = 40.f ;
		TEMP:C_format = "%9.3f" ;
		TEMP:FORTRAN_format = "F9.3" ;
		TEMP:resolution = 0.001f ;
```

This would be very useful for 3rd party libraries trying to check or double-check data returned by web API such as Ifremer erddap, Euro-Argo dataselection or argovis

**Comment by tcarval** [comment]
@gmaze , Guillaume, do you want to see the full list of variable attributes in the NVS table R03 
With the [TEMP example](https://vocab.nerc.ac.uk/collection/R03/current/TEMP/), these attributes are not available :

__TEMP:FillValue = 99999.f ;
TEMP:units = "degree_Celsius" ;
TEMP:valid_min = -2.5f ;
TEMP:valid_max = 40.f ;
TEMP:C_format = "%9.3f" ;
TEMP:FORTRAN_format = "F9.3" ;
TEMP:resolution = 0.001f ;_

**Comment by tcarval** [comment]
These 5 tickets address similar topic : https://github.com/nvs-vocabs/ArgoVocabs/issues/78 https://github.com/nvs-vocabs/ArgoVocabs/issues/57 https://github.com/nvs-vocabs/ArgoVocabs/issues/95 https://github.com/nvs-vocabs/ArgoVocabs/issues/74 https://github.com/nvs-vocabs/ArgoVocabs/issues/98

I close 4 of them and keep https://github.com/nvs-vocabs/ArgoVocabs/issues/57

**Comment by gmaze** [comment]
Yes if these information are not available elsewhere
