### ISSUE TITLE
Should R03 entries include whether the parameter is a core (c), BGC (b) or intermediate (i) parameter?

### ISSUE THREAD

**Issue by matdon17** [nvs-vocabs/ArgoVocabs#98]
Each parameter is defined as being either:
 - core (c)
 - BGC (b)
 - intermediate (i)

This is stated in the Argo user manual, as well in various cookbooks such as the individual BGC cookbooks.  However, this information is not captured in the NVS.  Should it be?

And if so, should it be via free-text additions to the R03 concept descriptions, or through a mapping to a new parameter type vocab?

**Comment by tcarval** [comment]
These 5 tickets address similar topic : https://github.com/nvs-vocabs/ArgoVocabs/issues/78 https://github.com/nvs-vocabs/ArgoVocabs/issues/57 https://github.com/nvs-vocabs/ArgoVocabs/issues/95 https://github.com/nvs-vocabs/ArgoVocabs/issues/74 https://github.com/nvs-vocabs/ArgoVocabs/issues/98

I close 4 of them and keep https://github.com/nvs-vocabs/ArgoVocabs/issues/57
